### ISSUE TITLE
videoInput.getPixels() Error: Could not get pixels

### ISSUE THREAD

**Issue by atena2019** [sagioto/LipReading#15]
Exception in thread "Thread-6" java.lang.RuntimeException: com.googlecode.javacv
.FrameGrabber$Exception: videoInput.getPixels() Error: Could not get pixels.
        at edu.lipreading.gui.VideoCapturePanel$1.run(VideoCapturePanel.java:94)

```
    at java.lang.Thread.run(Unknown Source)
```

Caused by: com.googlecode.javacv.FrameGrabber$Exception: videoInput.getPixels()
Error: Could not get pixels.
        at com.googlecode.javacv.VideoInputFrameGrabber.grab(VideoInputFrameGrab
ber.java:168)
        at edu.lipreading.gui.LipReaderPanel.getVideoFromSource(LipReaderPanel.j
ava:137)
        at edu.lipreading.gui.VideoCapturePanel$1.run(VideoCapturePanel.java:92)

```
    ... 1 more
```

sometimes i have this error, but some times not. when i restart or hibernate my windows, the first time that i run the program, it works but after that i get this error. what is the reason?

**Comment by atena2019** [comment]
i solved it.
in class edu.lipreading.vision.AbstractFeatureExtractor i replaced 
grabber = VideoInputFrameGrabber.createDefault(0);
with 
grabber = new OpenCVFrameGrabber(0);
