### ISSUE TITLE
Exception Exception is not compatible with throws clause in Server.main(String[])

### ISSUE THREAD

**Issue by NivedhaKHJ** [sagioto/LipReading#3]
The line 117 of WebFeatureExtractor "public static void main(String[] args) throws Exception" reports the error "Exception Exception is not compatible with throws clause in Server.main(String[])" .

Some one help me pls ?

**Comment by dagansandler** [comment]
This seems weird, what is your setup?

Try removing the throws declaration from WebFeatureExtractor.main(String[]) and see if it compiles then or what error it gives out.

**Comment by NivedhaKHJ** [comment]
If I remove the throws declaration from WebFeatureExtractor.main(String[]) , then the line
server.start(); reports the error "Unhandled exception type Exception " and the line
server.join(); reports the error "Unhandled exception type InterruptedException"

What s the mistake ?

**Comment by NivedhaKHJ** [comment]
Now That i have solved my above problem., now wen I run the code I am getting another error : 

Exception in thread "main" java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at com.googlecode.javacpp.Loader.load(Loader.java:553)
    at com.googlecode.javacpp.Loader.load(Loader.java:532)
    at com.googlecode.javacv.cpp.opencv_core$CvRect.<clinit>(opencv_core.java:2005)
    at edu.lipreading.vision.NoMoreStickersFeatureExtractor.<init>(NoMoreStickersFeatureExtractor.java:53)
    at edu.lipreading.WebFeatureExtractor.<clinit>(WebFeatureExtractor.java:30)
Caused by: java.lang.IllegalStateException: Can't overwrite cause
    at java.lang.Throwable.initCause(Throwable.java:456)
    at com.googlecode.javacpp.Loader.load(Loader.java:581)
    at com.googlecode.javacpp.Loader.load(Loader.java:532)
    at com.googlecode.javacv.cpp.opencv_core.<clinit>(opencv_core.java:134)
    ... 7 more
