### ISSUE TITLE
error in NoMoreStickersFeatureExtractor

### ISSUE THREAD

**Issue by NivedhaKHJ** [sagioto/LipReading#5]
Exception in thread "main" java.lang.ExceptionInInitializerError
    at main.java.edu.lipreading.vision.NoMoreStickersFeatureExtractor.init(NoMoreStickersFeatureExtractor.java:216)
    at main.java.edu.lipreading.vision.NoMoreStickersFeatureExtractor.getPoints(NoMoreStickersFeatureExtractor.java:70)
    at main.java.edu.lipreading.vision.AbstractFeatureExtractor.getPoints(AbstractFeatureExtractor.java:82)
    at main.java.edu.lipreading.vision.AbstractFeatureExtractor.extract(AbstractFeatureExtractor.java:37)
    at main.java.edu.lipreading.vision.NoMoreStickersFeatureExtractor.main(NoMoreStickersFeatureExtractor.java:390)
Caused by: java.lang.NullPointerException
    at java.util.Properties$LineReader.readLine(Unknown Source)
    at java.util.Properties.load0(Unknown Source)
    at java.util.Properties.load(Unknown Source)
    at main.java.edu.lipreading.Constants.<clinit>(Constants.java:16)
    ... 5 more

****\* VIDEOINPUT LIBRARY - 0.1995 - TFW07 *****

SETUP: Setting up device 0
SETUP: 1.3M HD WebCam
SETUP: Couldn't find preview pin using SmartTee
SETUP: Capture callback set
SETUP: Device is setup and ready to capture.

Can someone help me ??

**Comment by sameer05k21a0440** [comment]
Hi,

```
     I have download you are application ,when i have run live feed , i got File Not Found Exception , so could you please send me Model file , which you have already created ? or else let me know how to done Model File ?
```

Thanks and Regards
sameer
sameersoft6@gmail.com

**Comment by sameer05k21a0440** [comment]
Hi,

```
     I have download you are application ,when i have run live feed , i got File Not Found Exception , so could you please send me Model file , which you have already created ? or else let me know how to done Model File ?
```

D:\Drop box\Lip Reading\XML s\models\yes No Hello\yes No Hello D a g a n. model 
Thanks and Regards
sameer
sameersoft6@gmail.com
