### ISSUE TITLE
java.io.FileNotFoundException:D:\Dropbox\LipReading\XMLs\models\yesNoHello\yesNoHelloDagan.model

### ISSUE THREAD

**Issue by sameer05k21a0440** [sagioto/LipReading#6]
Hi,

```
     I have download you are application ,when i have run live feed , i got File Not Found Exception , so could you please send me Model file , which you have already created ? or else let me know how to done Model File ?
```

Thanks and Regards
sameer
sameersoft6@gmail.com

**Comment by atena2019** [comment]
do u now how can i create yesNoHelloDagan.model?

**Comment by sameer05k21a0440** [comment]
Hi,

```
    I knew how to create .model file , download weka tools 3.6.7
```

version .

**Comment by atena2019** [comment]
can u please send me a tutorial for creating model files? i do not know how can i create it. what are input files? .xml files or video of lip files?

**Comment by sameer05k21a0440** [comment]
Hi,

```
       For creating .model u need to use Weka Tool .
```

Thanks

**Comment by dorleitman** [comment]
Please check out our documents page in our project`s website: http://dorleitma1.wix.com/lipreading
You can find some info about working with Weka in "User Guide" and "Maintainers Guide".

**Comment by atena2019** [comment]
thanks a lot.
the command 
java –jar lipreading-core.jar –train <inputtrainingset.zip> <output.model>
does not work. what should i do?

**Comment by sameer05k21a0440** [comment]
May i know what error you got ?

**Comment by atena2019** [comment]
when i run that command in cmd on windows, nothing happens. no error, no message, no warning, and nothing happens. but the command for generating arff file worked properly

**Comment by sameer05k21a0440** [comment]
Are you generated .arff file ?

Note : for Discussion about project convience please add me Gmail /Skype ?
Gmail E-mail ID :sameersoft6@gmail.com
Skype ID : sameer.ahamed60

Thanks
sameer

**Comment by atena2019** [comment]
yes, i did.

**Comment by atena2019** [comment]
how can i  generate .model using weka explorer and this arff file? should i select a specific clasification method?

**Comment by sameer05k21a0440** [comment]
using weka tool  ->upload .arff file -> from classifier ->function

> inactive smo select - >norm word select ->click start button ->then right
> click mouse button ->save model file .

May I know you are from ?
for what purpose doing ?
You are good name ?
Thanks
sameer

**Comment by atena2019** [comment]
Thank you very much for your time and patience 
i downloaded weka 3.6.7 and i opened weka explorer, then loaded my .arff file and in classify tab, from classifiers i selected SMO. but SMO is inactive and i can not see norm word. and start button is inactive so. what should i do? (sorry i never worked with weka before)

I am an MSC student working on lip reading for Android Smartphones. My first name is Adele, but for my github i choosed Atena. your project is very good( i saw documentation and video) and i'd like to run it to know more about that.

**Comment by atena2019** [comment]
may i have an image from your weka explorer that shows the parameters you used for classification?

**Comment by sameer05k21a0440** [comment]
Hi Adele ,

```
        you are right SMO inactive select it , from classify tab select
```

norm wrod  list then start button click .

You are from which country ?

About my self
I am from India
Name :Sameer
Skype ID :sameer.ahamed60
Linked In :
http://www.linkedin.com/profile/view?id=158974547&trk=nav_responsive_tab_profile_pic

Thanks

**Comment by atena2019** [comment]
hi
thanks
i found the answer. when i loaded the .arff file, i could not see any list with value nom word. it was beacause i  generated the .arff file with lipreadin-core.java -arff command. but i downloaded mp-10folds.model from https://dl.dropbox.com/u/8720454/weka/dataset2.arff
and i compared that with my generated .arff file. i found that in this arff file it says: 
@attribute word {hello,no,yes}
 but my generated arff file says:
@attribute word numeric
and because that all of my attributes are numeric, start never become active!

**Comment by atena2019** [comment]
now i have another problem. when i use "mp-10folds.model" as my model file for classification, i got this exception in constructor of WekaClassifier:
Exception in thread "Thread-8" java.lang.StackOverflowError
    at java.io.ObjectInputStream$BlockDataInputStream.readUnsignedShort(ObjectInputStream.java:2777)
    at java.io.ObjectInputStream$BlockDataInputStream.readUTF(ObjectInputStream.java:2837)
    at java.io.ObjectInputStream.readString(ObjectInputStream.java:1617)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1338)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1964)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1888)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
    at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1685)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1341)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1964)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1888)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
    at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1685)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1341)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1964)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1888)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
    at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1685)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1341)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1964)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1888)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
    at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1685)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1341)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1964)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1888)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
