### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniavcodec in java.library.path

### ISSUE THREAD

**Issue by atena2019** [sagioto/LipReading#8]
when try to run GetFileTest.java in test case readFromUrlTest() i got this exception:
java.lang.UnsatisfiedLinkError: no jniavcodec in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
    at java.lang.Runtime.loadLibrary0(Runtime.java:845)
    at java.lang.System.loadLibrary(System.java:1084)
    at com.googlecode.javacpp.Loader.loadLibrary(Loader.java:711)
    at com.googlecode.javacpp.Loader.load(Loader.java:586)
    at com.googlecode.javacpp.Loader.load(Loader.java:540)
    at com.googlecode.javacv.cpp.avcodec.<clinit>(avcodec.java:39)
    at com.googlecode.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:103)
    at edu.lipreading.vision.AbstractFeatureExtractor.getGrabber(AbstractFeatureExtractor.java:48)
    at edu.lipreading.vision.AbstractFeatureExtractor.extract(AbstractFeatureExtractor.java:34)
    at edu.lipreading.vision.GetFileTest.readFromUrlTest(GetFileTest.java:59)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\mgr\AppData\Local\Temp\javacpp84231122631068\jniavcodec.dll: The specified procedure could not be found
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1928)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
    at java.lang.Runtime.load0(Runtime.java:792)
    at java.lang.System.load(System.java:1059)
    at com.googlecode.javacpp.Loader.loadLibrary(Loader.java:700)
    ... 32 more

**Comment by atena2019** [comment]
do i need to install a library? i installed opencv 2.4.8 and javacv 0.7 and ffmpeg 0.7.1. anything more i need ?

**Comment by NivedhaKHJ** [comment]
Hello. are you getting the output in windows application ?? 
pls mail me : nivedha.mit@gmail.com

**Comment by atena2019** [comment]
Hi NivedhaKHJ
unfortunately not yet.i have mistake in classification. what about you?

**Comment by atena2019** [comment]
answer of my issue is that i should follow the instruction in wiki page to get correct version of libraries. it solved my problem

**Comment by NivedhaKHJ** [comment]
yea i got the output in windows. but not in android

**Comment by atena2019** [comment]
does it give you the correct  answer? 
i have mistake in classification. i have this exception:

java.lang.ArrayIndexOutOfBoundsException: 801
    at weka.filters.unsupervised.attribute.ReplaceMissingValues.convertInstance(ReplaceMissingValues.java:274)
    at weka.filters.unsupervised.attribute.ReplaceMissingValues.input(ReplaceMissingValues.java:140)
    at weka.classifiers.functions.SMO.distributionForInstance(SMO.java:1367)
    at edu.lipreading.classification.SVMClassifier.test(SVMClassifier.java:49)
    at edu.lipreading.gui.VideoCapturePanel.classify(VideoCapturePanel.java:154)
    at edu.lipreading.gui.FileLipReaderPanel$ClassifierThread$1.run(FileLipReaderPanel.java:220)
    at java.lang.Thread.run(Thread.java:722)

it is because of model file. but i do not konw why?
can you please send me your model file?how did you generate your model? using weka explorer or command?

**Comment by NivedhaKHJ** [comment]
i created the model file using weka explorer.

**Comment by atena2019** [comment]
the arff file and  model file has 801 attributes. but when i want to test a video, the created instance has 1204 attributes. have you changed the code to apply a filter to test instance data?

**Comment by atena2019** [comment]
i found the mistake. i changed the Frame_count in lr.properties from 150 to 100 to create test instance with 100*8 = 800 attributes. and i changed below function as this:(in WekaClaasifier class)

protected Instance sampleToInstance(Sample sample) {

```
    Instance instance = new DenseInstance(INSTANCE_SIZE-4);//-4 added by me
    instance.setMissing(0);

    for (int i = 0; i < INSTANCE_SIZE - Constants.SAMPLE_ROW_SHIFT; i++) {
        instance.setValue(i , sample.getMatrix().get(i / 8).get(i % 8));
    }        
    return instance;
}
```

**Comment by atena2019** [comment]
i found the mistake. i changed the Frame_count in lr.properties from 150 to 100 to create test instance with 100*8 = 800 attributes. and i changed below function as this:(in WekaClaasifier class)

protected Instance sampleToInstance(Sample sample) {

```
    Instance instance = new DenseInstance(INSTANCE_SIZE-4);//-4 added by me
    instance.setMissing(0);

    for (int i = 0; i < INSTANCE_SIZE - Constants.SAMPLE_ROW_SHIFT; i++) {
        instance.setValue(i , sample.getMatrix().get(i / 8).get(i % 8));
    }        
    return instance;
}
```

**Comment by atena2019** [comment]
Dear nivedha, does the windows version works correctly (without wrong response) for you? when i create my model file, the application can not classify my input correctly and it always returns one label. it even do not works when i use my train data as test data. is it related to code or my train input?
